name: file-organizer
channels:
  - defaults
dependencies:
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2025.12.2=hca03da5_0
  - expat=2.7.3=h50f4ffc_4
  - libcxx=21.1.8=hb4ce287_0
  - libexpat=2.7.3=h50f4ffc_4
  - libffi=3.4.4=hca03da5_1
  - libzlib=1.3.1=h5f15de7_0
  - ncurses=6.5=hee39554_0
  - openssl=3.0.19=ha0b305a_0
  - packaging=25.0=py311hca03da5_1
  - pip=25.3=pyhc872135_0
  - python=3.11.14=hf701271_0
  - readline=8.3=h0b18652_0
  - setuptools=80.10.1=py311hca03da5_0
  - sqlite=3.51.1=hab6afd1_0
  - tk=8.6.15=hcd8a7d5_0
  - tzdata=2025c=he532380_0
  - wheel=0.46.3=py311hca03da5_0
  - xz=5.6.4=h80987f9_1
  - zlib=1.3.1=h5f15de7_0
  - pip:
      - annotated-types==0.7.0
      - certifi==2026.1.4
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - cryptography==46.0.4
      - google-ai-generativelanguage==0.6.15
      - google-api-core==2.29.0
      - google-api-python-client==2.188.0
      - google-auth==2.49.0.dev0
      - google-auth-httplib2==0.3.0
      - google-generativeai==0.8.6
      - googleapis-common-protos==1.72.0
      - grpcio==1.76.0
      - grpcio-status==1.71.2
      - httplib2==0.31.2
      - idna==3.11
      - lxml==6.0.2
      - pillow==12.1.0
      - proto-plus==1.27.0
      - protobuf==5.29.5
      - pyasn1==0.6.2
      - pyasn1-modules==0.4.2
      - pycparser==3.0
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pydf==12
      - pyparsing==3.3.2
      - python-docx==1.2.0
      - python-dotenv==1.2.1
      - requests==2.32.5
      - tqdm==4.67.2
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - uritemplate==4.2.0
      - urllib3==2.6.3
prefix: /opt/miniconda3/envs/file-organizer
